"""
Synthetic JD Generator
======================
Replaces existing JD files with clean, structured, English JDs
generated by Gemini API.

Each JD will have:
  - Clear role title
  - Company context (fictional but realistic)
  - Required skills (must-have, 5-8 skills)
  - Preferred skills (nice-to-have, 3-5 skills)
  - Experience range
  - Responsibilities
  - Education requirement

Existing filenames are PRESERVED — your Excel labels stay valid.

Usage:
  pip install google-generativeai
  python backend/generate_jds.py

Set your Gemini API key:
  Windows:   set GEMINI_API_KEY=your_key
  Mac/Linux: export GEMINI_API_KEY=your_key
"""

import os
import re
import time
import json
import google.generativeai as genai

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
JDS_DIR    = os.path.join(BASE_DIR, "jds")
INDEX_FILE = os.path.join(BASE_DIR, "jds_index.csv")

# Role templates — used to generate varied, realistic JDs
ROLE_TEMPLATES = {
    "frontend": [
        ("Frontend Developer",          "React",          "2-4 years"),
        ("Senior Frontend Engineer",     "Vue.js",         "4-6 years"),
        ("UI Engineer",                  "Angular",        "2-4 years"),
        ("Junior Frontend Developer",    "React",          "0-2 years"),
        ("Frontend Tech Lead",           "React/Next.js",  "5-8 years"),
    ],
    "backend": [
        ("Backend Engineer",             "Node.js",        "2-4 years"),
        ("Senior Backend Developer",     "Python/Django",  "4-6 years"),
        ("Java Backend Engineer",        "Spring Boot",    "3-5 years"),
        ("Backend Engineer",             "Golang",         "2-4 years"),
        ("Senior API Engineer",          "FastAPI",        "3-6 years"),
    ],
    "data": [
        ("Data Analyst",                 "SQL/Python",     "1-3 years"),
        ("Senior Data Analyst",          "Tableau/Python", "3-5 years"),
        ("Business Intelligence Analyst","Power BI",       "2-4 years"),
        ("Data Analyst Intern",          "Excel/SQL",      "0-1 years"),
        ("Marketing Data Analyst",       "SQL/GA4",        "2-4 years"),
    ],
    "ml": [
        ("Machine Learning Engineer",    "PyTorch",        "2-4 years"),
        ("ML Engineer Intern",           "Python/sklearn", "0-1 years"),
        ("NLP Engineer",                 "Transformers",   "2-5 years"),
        ("Senior ML Engineer",           "TensorFlow",     "4-7 years"),
        ("AI Research Engineer",         "PyTorch/JAX",    "3-6 years"),
    ],
    "qa": [
        ("QA Engineer",                  "Selenium",       "1-3 years"),
        ("Senior QA Automation Engineer","Cypress",        "3-5 years"),
        ("SDET",                         "Playwright",     "2-4 years"),
        ("QA Engineer Intern",           "Manual Testing", "0-1 years"),
        ("Performance Test Engineer",    "JMeter/k6",      "2-5 years"),
    ],
    "devops": [
        ("DevOps Engineer",              "AWS/Terraform",  "2-4 years"),
        ("Senior Cloud Engineer",        "GCP/Kubernetes", "4-6 years"),
        ("Platform Engineer",            "AWS/Docker",     "3-5 years"),
        ("Site Reliability Engineer",    "Kubernetes",     "3-6 years"),
        ("DevOps Intern",                "Linux/Docker",   "0-1 years"),
    ],
}

COMPANIES = [
    "TechNova Solutions", "CloudBridge Inc", "DataSpark Labs",
    "NexGen Systems", "Velocity Software", "Apex Digital",
    "CoreStack Technologies", "Brightline AI", "Momentum Tech",
    "Pinnacle Engineering", "BlueSky Platforms", "Orbit Solutions",
    "GridIron Software", "Quantum Builds", "Helix Technologies",
]

JD_PROMPT = """Generate a realistic, professional job description for the following role.

Role: {role}
Primary Tech Stack: {stack}
Experience Required: {experience}
Company: {company}

Return ONLY a JSON object with this exact structure (no markdown, no extra text):
{{
  "role_title": "exact job title",
  "company_overview": "2-3 sentences about the fictional company and what they do",
  "responsibilities": [
    "responsibility 1",
    "responsibility 2",
    "responsibility 3",
    "responsibility 4",
    "responsibility 5"
  ],
  "required_skills": [
    "skill 1 (be specific, e.g. React 18+, not just React)",
    "skill 2",
    "skill 3",
    "skill 4",
    "skill 5",
    "skill 6"
  ],
  "preferred_skills": [
    "nice-to-have skill 1",
    "nice-to-have skill 2",
    "nice-to-have skill 3"
  ],
  "experience_range": "{experience}",
  "education": "education requirement",
  "salary_range": "realistic USD salary range for this role"
}}

Rules:
- All content must be in English
- Skills must be specific technologies, not vague terms
- Required skills = must have to do the job
- Preferred skills = bonus, not dealbreaker
- Keep it realistic and professional
- Do not include any personally identifying information
"""


def detect_role(filename):
    fname = filename.lower()
    for role in ROLE_TEMPLATES:
        if role in fname:
            return role
    return None


def format_jd(meta, data):
    """Format parsed JSON into clean readable JD text."""
    lines = [
        f"ROLE: {data['role_title']}",
        f"SOURCE: Synthetic",
        f"URL: N/A",
        f"COMPANY: {meta['company']}",
        "",
        "=" * 60,
        f"  {data['role_title'].upper()}",
        f"  {meta['company']}",
        "=" * 60,
        "",
        "ABOUT THE COMPANY",
        "-" * 40,
        data.get("company_overview", ""),
        "",
        "RESPONSIBILITIES",
        "-" * 40,
    ]
    for r in data.get("responsibilities", []):
        lines.append(f"  • {r}")

    lines += [
        "",
        "REQUIRED SKILLS (Must-Have)",
        "-" * 40,
    ]
    for s in data.get("required_skills", []):
        lines.append(f"  ✅ {s}")

    lines += [
        "",
        "PREFERRED SKILLS (Nice-to-Have)",
        "-" * 40,
    ]
    for s in data.get("preferred_skills", []):
        lines.append(f"  ⭐ {s}")

    lines += [
        "",
        "EXPERIENCE & EDUCATION",
        "-" * 40,
        f"  Experience: {data.get('experience_range', meta['experience'])}",
        f"  Education:  {data.get('education', 'Bachelor degree or equivalent')}",
        "",
        "COMPENSATION",
        "-" * 40,
        f"  {data.get('salary_range', 'Competitive, based on experience')}",
        "",
    ]
    return "\n".join(lines)


def generate_jd(model, role, stack, experience, company):
    """Call Gemini API to generate one JD."""
    prompt = JD_PROMPT.format(
        role=role, stack=stack,
        experience=experience, company=company
    )
    response = model.generate_content(prompt)
    raw = response.text.strip()
    # Strip markdown fences if present
    raw = re.sub(r'^```json\s*', '', raw)
    raw = re.sub(r'^```\s*',     '', raw)
    raw = re.sub(r'\s*```$',     '', raw)
    return json.loads(raw)


def run():
    api_key = "AIzaSyCE1Da0jcuKwXSoD5yl_8q_C4t9u7drfTE"
    if not api_key:
        print("❌ GEMINI_API_KEY not set.")
        print("   Windows:   set GEMINI_API_KEY=your_key")
        print("   Mac/Linux: export GEMINI_API_KEY=your_key")
        return

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")  # fast + cheap for bulk generation

    # Get all existing JD files
    jd_files = sorted([
        f for f in os.listdir(JDS_DIR)
        if f.endswith(".txt")
    ])

    if not jd_files:
        print(f"❌ No JD files found in {JDS_DIR}/")
        print("   Run jd_scraper.py first to create the files,")
        print("   then run this script to replace their content.")
        return

    print("=" * 60)
    print("  Synthetic JD Generator")
    print("=" * 60)
    print(f"\n📋 Found {len(jd_files)} JD files to replace")
    print("   Filenames will be preserved — Excel labels stay valid\n")

    # Build role assignment for each file
    # Cycle through role templates so each role gets variety
    role_counters = {r: 0 for r in ROLE_TEMPLATES}
    company_idx   = 0
    assignments   = []

    for fname in jd_files:
        role = detect_role(fname)
        if not role:
            role = list(ROLE_TEMPLATES.keys())[len(assignments) % len(ROLE_TEMPLATES)]

        templates    = ROLE_TEMPLATES[role]
        template_idx = role_counters[role] % len(templates)
        tpl_role, tpl_stack, tpl_exp = templates[template_idx]

        assignments.append({
            "fname":      fname,
            "role":       tpl_role,
            "stack":      tpl_stack,
            "experience": tpl_exp,
            "company":    COMPANIES[company_idx % len(COMPANIES)],
            "role_cat":   role,
        })
        role_counters[role] += 1
        company_idx         += 1

    # Generate and save
    success = 0
    failed  = 0

    for i, meta in enumerate(assignments, 1):
        fpath = os.path.join(JDS_DIR, meta["fname"])
        print(f"  [{i:02d}/{len(assignments)}] Generating: {meta['role']} @ {meta['company']}")

        try:
            data       = generate_jd(model, meta["role"], meta["stack"],
                                     meta["experience"], meta["company"])
            jd_text    = format_jd(meta, data)

            with open(fpath, "w", encoding="utf-8") as f:
                f.write(jd_text)

            char_count = len(jd_text)
            print(f"         ✅ Saved → {meta['fname']} ({char_count} chars)")
            success += 1

        except json.JSONDecodeError as e:
            print(f"         ⚠️  JSON parse error — keeping original file. ({e})")
            failed += 1
        except Exception as e:
            print(f"         ❌ Failed: {e}")
            failed += 1

        time.sleep(0.3)  # avoid rate limiting

    print(f"\n{'='*60}")
    print(f"  ✅ Generated: {success} JDs")
    print(f"  ❌ Failed:    {failed} JDs")
    print(f"\n  Your Excel labels are still valid.")
    print(f"  All JDs are now in English with structured skills.")
    print("=" * 60)


if __name__ == "__main__":
    run()